###
# Test the swap endpoint
POST http://localhost:1337/blinks/swap?inputMint=So11111111111111111111111111111111111111112&outputMint=4k3Dyjzvzp8e2WXLDwK8bkgGoGNt5UPTadMsRDp4y5Nn&amount=1000000&slippageBps=100
Content-Type: application/json

{
  "account": "HFJEhqTUPKKWvhwVeQS5qjSP373kMUFpNuiqMMyXZ2Gr"
}

###
# Test the transfer-sol endpoint
POST http://localhost:1337/blinks/transfer-sol?amount=1&to=HFJEhqTUPKKWvhwVeQS5qjSP373kMUFpNuiqMMyXZ2Gr
Content-Type: application/json

{
  "account": "HFJEhqTUPKKWvhwVeQS5qjSP373kMUFpNuiqMMyXZ2Gr"
}

###
# Test getting the transfer-sol endpoint information
GET http://localhost:1337/blinks/transfer-sol
Accept: application/json

###
# Test the stake SOL endpoint for Solana
POST http://localhost:1337/blinks/stake?validatorPubkey=FRnC8BfQzz63cCyQGE8TxJrDEc5cFQ8SnJgdEzK36uG3&amount=1
Content-Type: application/json

{
    "account": "HFJEhqTUPKKWvhwVeQS5qjSP373kMUFpNuiqMMyXZ2Gr"
}

###
# Test getting the stake SOL endpoint information
GET http://localhost:1337/blinks/stake
Accept: application/json

###
# Test the stake BONK endpoint
POST http://localhost:1337/blinks/stake-bonk?amount=1000&days=30
Content-Type: application/json

{
    "account": "4RFG4gnF64dQyH3YFnKjcTcXL7HKosRCsu6GFfGwim5L"
}

###
# Test getting the stake BONK endpoint information
GET http://localhost:1337/blinks/stake-bonk
Accept: application/json

###
# Test the memo endpoint with OPTIONS method
OPTIONS http://localhost:1337/blinks/memo?message=la%20pura%20ondita
Content-Type: application/json

###
# Test the memo endpoint with POST method
POST http://localhost:1337/blinks/memo?message=la%20pura%20ondita
Content-Type: application/json

{
  "account": "HFJEhqTUPKKWvhwVeQS5qjSP373kMUFpNuiqMMyXZ2Gr"
}

###
# Test getting the memo endpoint information
GET http://localhost:1337/blinks/memo
Accept: application/json

###
# Test getting the actions JSON root
GET http://localhost:1337/actions.json
Accept: application/json


###
# Test the quotes endpoint
GET http://localhost:1337/tokens/quotes?inputMint=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&outputMint=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
Accept: application/json

###
# Test create limit order
POST http://localhost:1337/blinks/create-limit-order?inputMint=So11111111111111111111111111111111111111112&outputMint=EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&inAmount=1&outAmount=200&expiredAt=2024-10-16T00:32
Content-Type: application/json

{
    "account": "HFJEhqTUPKKWvhwVeQS5qjSP373kMUFpNuiqMMyXZ2Gr"
}


